!SKD11のデータ
finish
*SET,ym%ARG2%,210e9    !ヤング率
*SET,er%ARG2%,1E-7    !電気抵抗率?
*SET,rp%ARG2%,100    !比透磁率?
*SET,pr%ARG2%,0.3    !ポアソン比
*SET,d%ARG2%,7730    !密度
/PREP7
mpdata,ex,ARG1,,ym%ARG2%   !ヤング率
mpdata,prxy,ARG1,,pr%ARG2%   !ポアソン比
TB,PLASTIC,ARG1,1,2,MISO       ! Activate TB,PLASTIC data table
!真ひずみ―真応力で入力すること，なお塑性変形が開始する点．この際塑性ひずみは0とすること
!データ点間の傾きが負にならないようにすること．つまり最大引張応力までのプロット
TBPT,DEFI,0,500E+6,!plot1
TBPT,DEFI,2,500E+6,!plot12 過剰な変形を抑える補完点(ひずみ200％)
finish
